/*
 * Bamboo
 * This is the reference document for the Atlassian Bamboo REST API. The REST API is for developers who want to:    - integrate Bamboo with other applications;   - create scripts that interact with Bamboo; or   - develop plugins that enhance the Bamboo UI, using REST to interact with the backend.    You can read more about developing Bamboo plugins in the [Bamboo Developer Documentation](https://developer.atlassian.com/bamboo/server/docs/latest/).
 *
 * The version of the OpenAPI document: 9.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package me.glindholm.mylyn.bamboo.internal.rest.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Arrays;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * JiraType
 */
@JsonPropertyOrder({
  JiraType.JSON_PROPERTY_TYPE_ICON_URL,
  JiraType.JSON_PROPERTY_TYPE_DESCRIPTION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class JiraType implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_TYPE_ICON_URL = "typeIconUrl";
  private String typeIconUrl;

  public static final String JSON_PROPERTY_TYPE_DESCRIPTION = "typeDescription";
  private String typeDescription;

  public JiraType() { 
  }

  public JiraType typeIconUrl(String typeIconUrl) {
    this.typeIconUrl = typeIconUrl;
    return this;
  }

   /**
   * Get typeIconUrl
   * @return typeIconUrl
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_TYPE_ICON_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTypeIconUrl() {
    return typeIconUrl;
  }


  @JsonProperty(JSON_PROPERTY_TYPE_ICON_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTypeIconUrl(String typeIconUrl) {
    this.typeIconUrl = typeIconUrl;
  }


  public JiraType typeDescription(String typeDescription) {
    this.typeDescription = typeDescription;
    return this;
  }

   /**
   * Get typeDescription
   * @return typeDescription
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_TYPE_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTypeDescription() {
    return typeDescription;
  }


  @JsonProperty(JSON_PROPERTY_TYPE_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTypeDescription(String typeDescription) {
    this.typeDescription = typeDescription;
  }


  /**
   * Return true if this JiraType object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JiraType jiraType = (JiraType) o;
    return Objects.equals(this.typeIconUrl, jiraType.typeIconUrl) &&
        Objects.equals(this.typeDescription, jiraType.typeDescription);
  }

  @Override
  public int hashCode() {
    return Objects.hash(typeIconUrl, typeDescription);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JiraType {\n");
    sb.append("    typeIconUrl: ").append(toIndentedString(typeIconUrl)).append("\n");
    sb.append("    typeDescription: ").append(toIndentedString(typeDescription)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

