/*
 * Bamboo
 * This is the reference document for the Atlassian Bamboo REST API. The REST API is for developers who want to:    - integrate Bamboo with other applications;   - create scripts that interact with Bamboo; or   - develop plugins that enhance the Bamboo UI, using REST to interact with the backend.    You can read more about developing Bamboo plugins in the [Bamboo Developer Documentation](https://developer.atlassian.com/bamboo/server/docs/latest/).
 *
 * The version of the OpenAPI document: 9.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package me.glindholm.mylyn.bamboo.internal.rest.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Arrays;
import me.glindholm.mylyn.bamboo.internal.rest.model.RestBruteForceProtection;
import me.glindholm.mylyn.bamboo.internal.rest.model.RestManualEncryptionConfiguration;
import me.glindholm.mylyn.bamboo.internal.rest.model.RestRssSecurityConfiguration;
import me.glindholm.mylyn.bamboo.internal.rest.model.RestSignUp;
import me.glindholm.mylyn.bamboo.internal.rest.model.RestXsrfProtection;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * RestSecuritySettings
 */
@JsonPropertyOrder({
  RestSecuritySettings.JSON_PROPERTY_SIGN_UP,
  RestSecuritySettings.JSON_PROPERTY_DISPLAY_CONTACT_DETAILS_ENABLED,
  RestSecuritySettings.JSON_PROPERTY_RESTRICTED_ADMINISTRATOR_ROLE_ENABLED,
  RestSecuritySettings.JSON_PROPERTY_SOX_COMPLIANCE_MODE_ENABLED,
  RestSecuritySettings.JSON_PROPERTY_BRUTE_FORCE_PROTECTION,
  RestSecuritySettings.JSON_PROPERTY_XSRF_PROTECTION,
  RestSecuritySettings.JSON_PROPERTY_RESOLVE_ARTIFACTS_CONTENT_TYPE_BY_EXTENSION_ENABLED,
  RestSecuritySettings.JSON_PROPERTY_MANAGE_ACCEPTED_SSH_HOST_KEYS,
  RestSecuritySettings.JSON_PROPERTY_SHOW_AUTHORS_DETAILS_TO_USERS,
  RestSecuritySettings.JSON_PROPERTY_UNAUTHENTICATED_REMOTE_TRIGGER_ALLOWED,
  RestSecuritySettings.JSON_PROPERTY_AGENT_ASSIGNMENT_MODIFICATION_BY_USERS_ALLOWED,
  RestSecuritySettings.JSON_PROPERTY_RSS_SECURITY_CONFIGURATION,
  RestSecuritySettings.JSON_PROPERTY_MANUAL_ENCRYPTION_CONFIGURATION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class RestSecuritySettings implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_SIGN_UP = "signUp";
  private RestSignUp signUp;

  public static final String JSON_PROPERTY_DISPLAY_CONTACT_DETAILS_ENABLED = "displayContactDetailsEnabled";
  private Boolean displayContactDetailsEnabled;

  public static final String JSON_PROPERTY_RESTRICTED_ADMINISTRATOR_ROLE_ENABLED = "restrictedAdministratorRoleEnabled";
  private Boolean restrictedAdministratorRoleEnabled;

  public static final String JSON_PROPERTY_SOX_COMPLIANCE_MODE_ENABLED = "soxComplianceModeEnabled";
  private Boolean soxComplianceModeEnabled;

  public static final String JSON_PROPERTY_BRUTE_FORCE_PROTECTION = "bruteForceProtection";
  private RestBruteForceProtection bruteForceProtection;

  public static final String JSON_PROPERTY_XSRF_PROTECTION = "xsrfProtection";
  private RestXsrfProtection xsrfProtection;

  public static final String JSON_PROPERTY_RESOLVE_ARTIFACTS_CONTENT_TYPE_BY_EXTENSION_ENABLED = "resolveArtifactsContentTypeByExtensionEnabled";
  private Boolean resolveArtifactsContentTypeByExtensionEnabled;

  public static final String JSON_PROPERTY_MANAGE_ACCEPTED_SSH_HOST_KEYS = "manageAcceptedSshHostKeys";
  private Boolean manageAcceptedSshHostKeys;

  public static final String JSON_PROPERTY_SHOW_AUTHORS_DETAILS_TO_USERS = "showAuthorsDetailsToUsers";
  private Boolean showAuthorsDetailsToUsers;

  public static final String JSON_PROPERTY_UNAUTHENTICATED_REMOTE_TRIGGER_ALLOWED = "unauthenticatedRemoteTriggerAllowed";
  private Boolean unauthenticatedRemoteTriggerAllowed;

  public static final String JSON_PROPERTY_AGENT_ASSIGNMENT_MODIFICATION_BY_USERS_ALLOWED = "agentAssignmentModificationByUsersAllowed";
  private Boolean agentAssignmentModificationByUsersAllowed;

  public static final String JSON_PROPERTY_RSS_SECURITY_CONFIGURATION = "rssSecurityConfiguration";
  private RestRssSecurityConfiguration rssSecurityConfiguration;

  public static final String JSON_PROPERTY_MANUAL_ENCRYPTION_CONFIGURATION = "manualEncryptionConfiguration";
  private RestManualEncryptionConfiguration manualEncryptionConfiguration;

  public RestSecuritySettings() { 
  }

  public RestSecuritySettings signUp(RestSignUp signUp) {
    this.signUp = signUp;
    return this;
  }

   /**
   * Get signUp
   * @return signUp
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_SIGN_UP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestSignUp getSignUp() {
    return signUp;
  }


  @JsonProperty(JSON_PROPERTY_SIGN_UP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignUp(RestSignUp signUp) {
    this.signUp = signUp;
  }


  public RestSecuritySettings displayContactDetailsEnabled(Boolean displayContactDetailsEnabled) {
    this.displayContactDetailsEnabled = displayContactDetailsEnabled;
    return this;
  }

   /**
   * Get displayContactDetailsEnabled
   * @return displayContactDetailsEnabled
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_DISPLAY_CONTACT_DETAILS_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDisplayContactDetailsEnabled() {
    return displayContactDetailsEnabled;
  }


  @JsonProperty(JSON_PROPERTY_DISPLAY_CONTACT_DETAILS_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisplayContactDetailsEnabled(Boolean displayContactDetailsEnabled) {
    this.displayContactDetailsEnabled = displayContactDetailsEnabled;
  }


  public RestSecuritySettings restrictedAdministratorRoleEnabled(Boolean restrictedAdministratorRoleEnabled) {
    this.restrictedAdministratorRoleEnabled = restrictedAdministratorRoleEnabled;
    return this;
  }

   /**
   * Get restrictedAdministratorRoleEnabled
   * @return restrictedAdministratorRoleEnabled
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_RESTRICTED_ADMINISTRATOR_ROLE_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getRestrictedAdministratorRoleEnabled() {
    return restrictedAdministratorRoleEnabled;
  }


  @JsonProperty(JSON_PROPERTY_RESTRICTED_ADMINISTRATOR_ROLE_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRestrictedAdministratorRoleEnabled(Boolean restrictedAdministratorRoleEnabled) {
    this.restrictedAdministratorRoleEnabled = restrictedAdministratorRoleEnabled;
  }


  public RestSecuritySettings soxComplianceModeEnabled(Boolean soxComplianceModeEnabled) {
    this.soxComplianceModeEnabled = soxComplianceModeEnabled;
    return this;
  }

   /**
   * Get soxComplianceModeEnabled
   * @return soxComplianceModeEnabled
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_SOX_COMPLIANCE_MODE_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSoxComplianceModeEnabled() {
    return soxComplianceModeEnabled;
  }


  @JsonProperty(JSON_PROPERTY_SOX_COMPLIANCE_MODE_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSoxComplianceModeEnabled(Boolean soxComplianceModeEnabled) {
    this.soxComplianceModeEnabled = soxComplianceModeEnabled;
  }


  public RestSecuritySettings bruteForceProtection(RestBruteForceProtection bruteForceProtection) {
    this.bruteForceProtection = bruteForceProtection;
    return this;
  }

   /**
   * Get bruteForceProtection
   * @return bruteForceProtection
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_BRUTE_FORCE_PROTECTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestBruteForceProtection getBruteForceProtection() {
    return bruteForceProtection;
  }


  @JsonProperty(JSON_PROPERTY_BRUTE_FORCE_PROTECTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBruteForceProtection(RestBruteForceProtection bruteForceProtection) {
    this.bruteForceProtection = bruteForceProtection;
  }


  public RestSecuritySettings xsrfProtection(RestXsrfProtection xsrfProtection) {
    this.xsrfProtection = xsrfProtection;
    return this;
  }

   /**
   * Get xsrfProtection
   * @return xsrfProtection
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_XSRF_PROTECTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestXsrfProtection getXsrfProtection() {
    return xsrfProtection;
  }


  @JsonProperty(JSON_PROPERTY_XSRF_PROTECTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setXsrfProtection(RestXsrfProtection xsrfProtection) {
    this.xsrfProtection = xsrfProtection;
  }


  public RestSecuritySettings resolveArtifactsContentTypeByExtensionEnabled(Boolean resolveArtifactsContentTypeByExtensionEnabled) {
    this.resolveArtifactsContentTypeByExtensionEnabled = resolveArtifactsContentTypeByExtensionEnabled;
    return this;
  }

   /**
   * Get resolveArtifactsContentTypeByExtensionEnabled
   * @return resolveArtifactsContentTypeByExtensionEnabled
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_RESOLVE_ARTIFACTS_CONTENT_TYPE_BY_EXTENSION_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getResolveArtifactsContentTypeByExtensionEnabled() {
    return resolveArtifactsContentTypeByExtensionEnabled;
  }


  @JsonProperty(JSON_PROPERTY_RESOLVE_ARTIFACTS_CONTENT_TYPE_BY_EXTENSION_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResolveArtifactsContentTypeByExtensionEnabled(Boolean resolveArtifactsContentTypeByExtensionEnabled) {
    this.resolveArtifactsContentTypeByExtensionEnabled = resolveArtifactsContentTypeByExtensionEnabled;
  }


  public RestSecuritySettings manageAcceptedSshHostKeys(Boolean manageAcceptedSshHostKeys) {
    this.manageAcceptedSshHostKeys = manageAcceptedSshHostKeys;
    return this;
  }

   /**
   * Get manageAcceptedSshHostKeys
   * @return manageAcceptedSshHostKeys
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_MANAGE_ACCEPTED_SSH_HOST_KEYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getManageAcceptedSshHostKeys() {
    return manageAcceptedSshHostKeys;
  }


  @JsonProperty(JSON_PROPERTY_MANAGE_ACCEPTED_SSH_HOST_KEYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManageAcceptedSshHostKeys(Boolean manageAcceptedSshHostKeys) {
    this.manageAcceptedSshHostKeys = manageAcceptedSshHostKeys;
  }


  public RestSecuritySettings showAuthorsDetailsToUsers(Boolean showAuthorsDetailsToUsers) {
    this.showAuthorsDetailsToUsers = showAuthorsDetailsToUsers;
    return this;
  }

   /**
   * Get showAuthorsDetailsToUsers
   * @return showAuthorsDetailsToUsers
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_SHOW_AUTHORS_DETAILS_TO_USERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getShowAuthorsDetailsToUsers() {
    return showAuthorsDetailsToUsers;
  }


  @JsonProperty(JSON_PROPERTY_SHOW_AUTHORS_DETAILS_TO_USERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShowAuthorsDetailsToUsers(Boolean showAuthorsDetailsToUsers) {
    this.showAuthorsDetailsToUsers = showAuthorsDetailsToUsers;
  }


  public RestSecuritySettings unauthenticatedRemoteTriggerAllowed(Boolean unauthenticatedRemoteTriggerAllowed) {
    this.unauthenticatedRemoteTriggerAllowed = unauthenticatedRemoteTriggerAllowed;
    return this;
  }

   /**
   * Get unauthenticatedRemoteTriggerAllowed
   * @return unauthenticatedRemoteTriggerAllowed
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_UNAUTHENTICATED_REMOTE_TRIGGER_ALLOWED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getUnauthenticatedRemoteTriggerAllowed() {
    return unauthenticatedRemoteTriggerAllowed;
  }


  @JsonProperty(JSON_PROPERTY_UNAUTHENTICATED_REMOTE_TRIGGER_ALLOWED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnauthenticatedRemoteTriggerAllowed(Boolean unauthenticatedRemoteTriggerAllowed) {
    this.unauthenticatedRemoteTriggerAllowed = unauthenticatedRemoteTriggerAllowed;
  }


  public RestSecuritySettings agentAssignmentModificationByUsersAllowed(Boolean agentAssignmentModificationByUsersAllowed) {
    this.agentAssignmentModificationByUsersAllowed = agentAssignmentModificationByUsersAllowed;
    return this;
  }

   /**
   * Get agentAssignmentModificationByUsersAllowed
   * @return agentAssignmentModificationByUsersAllowed
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_AGENT_ASSIGNMENT_MODIFICATION_BY_USERS_ALLOWED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAgentAssignmentModificationByUsersAllowed() {
    return agentAssignmentModificationByUsersAllowed;
  }


  @JsonProperty(JSON_PROPERTY_AGENT_ASSIGNMENT_MODIFICATION_BY_USERS_ALLOWED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAgentAssignmentModificationByUsersAllowed(Boolean agentAssignmentModificationByUsersAllowed) {
    this.agentAssignmentModificationByUsersAllowed = agentAssignmentModificationByUsersAllowed;
  }


  public RestSecuritySettings rssSecurityConfiguration(RestRssSecurityConfiguration rssSecurityConfiguration) {
    this.rssSecurityConfiguration = rssSecurityConfiguration;
    return this;
  }

   /**
   * Get rssSecurityConfiguration
   * @return rssSecurityConfiguration
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_RSS_SECURITY_CONFIGURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestRssSecurityConfiguration getRssSecurityConfiguration() {
    return rssSecurityConfiguration;
  }


  @JsonProperty(JSON_PROPERTY_RSS_SECURITY_CONFIGURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRssSecurityConfiguration(RestRssSecurityConfiguration rssSecurityConfiguration) {
    this.rssSecurityConfiguration = rssSecurityConfiguration;
  }


  public RestSecuritySettings manualEncryptionConfiguration(RestManualEncryptionConfiguration manualEncryptionConfiguration) {
    this.manualEncryptionConfiguration = manualEncryptionConfiguration;
    return this;
  }

   /**
   * Get manualEncryptionConfiguration
   * @return manualEncryptionConfiguration
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_MANUAL_ENCRYPTION_CONFIGURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestManualEncryptionConfiguration getManualEncryptionConfiguration() {
    return manualEncryptionConfiguration;
  }


  @JsonProperty(JSON_PROPERTY_MANUAL_ENCRYPTION_CONFIGURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManualEncryptionConfiguration(RestManualEncryptionConfiguration manualEncryptionConfiguration) {
    this.manualEncryptionConfiguration = manualEncryptionConfiguration;
  }


  /**
   * Return true if this RestSecuritySettings object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestSecuritySettings restSecuritySettings = (RestSecuritySettings) o;
    return Objects.equals(this.signUp, restSecuritySettings.signUp) &&
        Objects.equals(this.displayContactDetailsEnabled, restSecuritySettings.displayContactDetailsEnabled) &&
        Objects.equals(this.restrictedAdministratorRoleEnabled, restSecuritySettings.restrictedAdministratorRoleEnabled) &&
        Objects.equals(this.soxComplianceModeEnabled, restSecuritySettings.soxComplianceModeEnabled) &&
        Objects.equals(this.bruteForceProtection, restSecuritySettings.bruteForceProtection) &&
        Objects.equals(this.xsrfProtection, restSecuritySettings.xsrfProtection) &&
        Objects.equals(this.resolveArtifactsContentTypeByExtensionEnabled, restSecuritySettings.resolveArtifactsContentTypeByExtensionEnabled) &&
        Objects.equals(this.manageAcceptedSshHostKeys, restSecuritySettings.manageAcceptedSshHostKeys) &&
        Objects.equals(this.showAuthorsDetailsToUsers, restSecuritySettings.showAuthorsDetailsToUsers) &&
        Objects.equals(this.unauthenticatedRemoteTriggerAllowed, restSecuritySettings.unauthenticatedRemoteTriggerAllowed) &&
        Objects.equals(this.agentAssignmentModificationByUsersAllowed, restSecuritySettings.agentAssignmentModificationByUsersAllowed) &&
        Objects.equals(this.rssSecurityConfiguration, restSecuritySettings.rssSecurityConfiguration) &&
        Objects.equals(this.manualEncryptionConfiguration, restSecuritySettings.manualEncryptionConfiguration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(signUp, displayContactDetailsEnabled, restrictedAdministratorRoleEnabled, soxComplianceModeEnabled, bruteForceProtection, xsrfProtection, resolveArtifactsContentTypeByExtensionEnabled, manageAcceptedSshHostKeys, showAuthorsDetailsToUsers, unauthenticatedRemoteTriggerAllowed, agentAssignmentModificationByUsersAllowed, rssSecurityConfiguration, manualEncryptionConfiguration);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestSecuritySettings {\n");
    sb.append("    signUp: ").append(toIndentedString(signUp)).append("\n");
    sb.append("    displayContactDetailsEnabled: ").append(toIndentedString(displayContactDetailsEnabled)).append("\n");
    sb.append("    restrictedAdministratorRoleEnabled: ").append(toIndentedString(restrictedAdministratorRoleEnabled)).append("\n");
    sb.append("    soxComplianceModeEnabled: ").append(toIndentedString(soxComplianceModeEnabled)).append("\n");
    sb.append("    bruteForceProtection: ").append(toIndentedString(bruteForceProtection)).append("\n");
    sb.append("    xsrfProtection: ").append(toIndentedString(xsrfProtection)).append("\n");
    sb.append("    resolveArtifactsContentTypeByExtensionEnabled: ").append(toIndentedString(resolveArtifactsContentTypeByExtensionEnabled)).append("\n");
    sb.append("    manageAcceptedSshHostKeys: ").append(toIndentedString(manageAcceptedSshHostKeys)).append("\n");
    sb.append("    showAuthorsDetailsToUsers: ").append(toIndentedString(showAuthorsDetailsToUsers)).append("\n");
    sb.append("    unauthenticatedRemoteTriggerAllowed: ").append(toIndentedString(unauthenticatedRemoteTriggerAllowed)).append("\n");
    sb.append("    agentAssignmentModificationByUsersAllowed: ").append(toIndentedString(agentAssignmentModificationByUsersAllowed)).append("\n");
    sb.append("    rssSecurityConfiguration: ").append(toIndentedString(rssSecurityConfiguration)).append("\n");
    sb.append("    manualEncryptionConfiguration: ").append(toIndentedString(manualEncryptionConfiguration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

