/*
 * Bamboo
 * This is the reference document for the Atlassian Bamboo REST API. The REST API is for developers who want to:    - integrate Bamboo with other applications;   - create scripts that interact with Bamboo; or   - develop plugins that enhance the Bamboo UI, using REST to interact with the backend.    You can read more about developing Bamboo plugins in the [Bamboo Developer Documentation](https://developer.atlassian.com/bamboo/server/docs/latest/).
 *
 * The version of the OpenAPI document: 9.3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package me.glindholm.mylyn.bamboo.internal.rest.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Arrays;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * VcsChangeDetectionOptions
 */
@JsonPropertyOrder({
  VcsChangeDetectionOptions.JSON_PROPERTY_QUIET_PERIOD,
  VcsChangeDetectionOptions.JSON_PROPERTY_QUIET_PERIOD_ENABLED,
  VcsChangeDetectionOptions.JSON_PROPERTY_MAX_RETRIES,
  VcsChangeDetectionOptions.JSON_PROPERTY_COMMIT_ISOLATION_ENABLED,
  VcsChangeDetectionOptions.JSON_PROPERTY_CHANGESET_FILTER_PATTERN_REGEX,
  VcsChangeDetectionOptions.JSON_PROPERTY_FILTER_FILE_PATTERN_OPTION,
  VcsChangeDetectionOptions.JSON_PROPERTY_FILTER_FILE_PATTERN_REGEX,
  VcsChangeDetectionOptions.JSON_PROPERTY_CONFIGURATION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class VcsChangeDetectionOptions implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_QUIET_PERIOD = "quietPeriod";
  private Integer quietPeriod;

  public static final String JSON_PROPERTY_QUIET_PERIOD_ENABLED = "quietPeriodEnabled";
  private Boolean quietPeriodEnabled;

  public static final String JSON_PROPERTY_MAX_RETRIES = "maxRetries";
  private Integer maxRetries;

  public static final String JSON_PROPERTY_COMMIT_ISOLATION_ENABLED = "commitIsolationEnabled";
  private Boolean commitIsolationEnabled;

  public static final String JSON_PROPERTY_CHANGESET_FILTER_PATTERN_REGEX = "changesetFilterPatternRegex";
  private String changesetFilterPatternRegex;

  public static final String JSON_PROPERTY_FILTER_FILE_PATTERN_OPTION = "filterFilePatternOption";
  private String filterFilePatternOption;

  public static final String JSON_PROPERTY_FILTER_FILE_PATTERN_REGEX = "filterFilePatternRegex";
  private String filterFilePatternRegex;

  public static final String JSON_PROPERTY_CONFIGURATION = "configuration";
  private Object _configuration;

  public VcsChangeDetectionOptions() { 
  }

  public VcsChangeDetectionOptions quietPeriod(Integer quietPeriod) {
    this.quietPeriod = quietPeriod;
    return this;
  }

   /**
   * Get quietPeriod
   * @return quietPeriod
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_QUIET_PERIOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getQuietPeriod() {
    return quietPeriod;
  }


  @JsonProperty(JSON_PROPERTY_QUIET_PERIOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuietPeriod(Integer quietPeriod) {
    this.quietPeriod = quietPeriod;
  }


  public VcsChangeDetectionOptions quietPeriodEnabled(Boolean quietPeriodEnabled) {
    this.quietPeriodEnabled = quietPeriodEnabled;
    return this;
  }

   /**
   * Get quietPeriodEnabled
   * @return quietPeriodEnabled
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_QUIET_PERIOD_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getQuietPeriodEnabled() {
    return quietPeriodEnabled;
  }


  @JsonProperty(JSON_PROPERTY_QUIET_PERIOD_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuietPeriodEnabled(Boolean quietPeriodEnabled) {
    this.quietPeriodEnabled = quietPeriodEnabled;
  }


  public VcsChangeDetectionOptions maxRetries(Integer maxRetries) {
    this.maxRetries = maxRetries;
    return this;
  }

   /**
   * Get maxRetries
   * @return maxRetries
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_MAX_RETRIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMaxRetries() {
    return maxRetries;
  }


  @JsonProperty(JSON_PROPERTY_MAX_RETRIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxRetries(Integer maxRetries) {
    this.maxRetries = maxRetries;
  }


  public VcsChangeDetectionOptions commitIsolationEnabled(Boolean commitIsolationEnabled) {
    this.commitIsolationEnabled = commitIsolationEnabled;
    return this;
  }

   /**
   * Get commitIsolationEnabled
   * @return commitIsolationEnabled
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_COMMIT_ISOLATION_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCommitIsolationEnabled() {
    return commitIsolationEnabled;
  }


  @JsonProperty(JSON_PROPERTY_COMMIT_ISOLATION_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommitIsolationEnabled(Boolean commitIsolationEnabled) {
    this.commitIsolationEnabled = commitIsolationEnabled;
  }


  public VcsChangeDetectionOptions changesetFilterPatternRegex(String changesetFilterPatternRegex) {
    this.changesetFilterPatternRegex = changesetFilterPatternRegex;
    return this;
  }

   /**
   * Get changesetFilterPatternRegex
   * @return changesetFilterPatternRegex
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_CHANGESET_FILTER_PATTERN_REGEX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getChangesetFilterPatternRegex() {
    return changesetFilterPatternRegex;
  }


  @JsonProperty(JSON_PROPERTY_CHANGESET_FILTER_PATTERN_REGEX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChangesetFilterPatternRegex(String changesetFilterPatternRegex) {
    this.changesetFilterPatternRegex = changesetFilterPatternRegex;
  }


  public VcsChangeDetectionOptions filterFilePatternOption(String filterFilePatternOption) {
    this.filterFilePatternOption = filterFilePatternOption;
    return this;
  }

   /**
   * Get filterFilePatternOption
   * @return filterFilePatternOption
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_FILTER_FILE_PATTERN_OPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFilterFilePatternOption() {
    return filterFilePatternOption;
  }


  @JsonProperty(JSON_PROPERTY_FILTER_FILE_PATTERN_OPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilterFilePatternOption(String filterFilePatternOption) {
    this.filterFilePatternOption = filterFilePatternOption;
  }


  public VcsChangeDetectionOptions filterFilePatternRegex(String filterFilePatternRegex) {
    this.filterFilePatternRegex = filterFilePatternRegex;
    return this;
  }

   /**
   * Get filterFilePatternRegex
   * @return filterFilePatternRegex
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_FILTER_FILE_PATTERN_REGEX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFilterFilePatternRegex() {
    return filterFilePatternRegex;
  }


  @JsonProperty(JSON_PROPERTY_FILTER_FILE_PATTERN_REGEX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilterFilePatternRegex(String filterFilePatternRegex) {
    this.filterFilePatternRegex = filterFilePatternRegex;
  }


  public VcsChangeDetectionOptions _configuration(Object _configuration) {
    this._configuration = _configuration;
    return this;
  }

   /**
   * Get _configuration
   * @return _configuration
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_CONFIGURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getConfiguration() {
    return _configuration;
  }


  @JsonProperty(JSON_PROPERTY_CONFIGURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConfiguration(Object _configuration) {
    this._configuration = _configuration;
  }


  /**
   * Return true if this VcsChangeDetectionOptions object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VcsChangeDetectionOptions vcsChangeDetectionOptions = (VcsChangeDetectionOptions) o;
    return Objects.equals(this.quietPeriod, vcsChangeDetectionOptions.quietPeriod) &&
        Objects.equals(this.quietPeriodEnabled, vcsChangeDetectionOptions.quietPeriodEnabled) &&
        Objects.equals(this.maxRetries, vcsChangeDetectionOptions.maxRetries) &&
        Objects.equals(this.commitIsolationEnabled, vcsChangeDetectionOptions.commitIsolationEnabled) &&
        Objects.equals(this.changesetFilterPatternRegex, vcsChangeDetectionOptions.changesetFilterPatternRegex) &&
        Objects.equals(this.filterFilePatternOption, vcsChangeDetectionOptions.filterFilePatternOption) &&
        Objects.equals(this.filterFilePatternRegex, vcsChangeDetectionOptions.filterFilePatternRegex) &&
        Objects.equals(this._configuration, vcsChangeDetectionOptions._configuration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(quietPeriod, quietPeriodEnabled, maxRetries, commitIsolationEnabled, changesetFilterPatternRegex, filterFilePatternOption, filterFilePatternRegex, _configuration);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VcsChangeDetectionOptions {\n");
    sb.append("    quietPeriod: ").append(toIndentedString(quietPeriod)).append("\n");
    sb.append("    quietPeriodEnabled: ").append(toIndentedString(quietPeriodEnabled)).append("\n");
    sb.append("    maxRetries: ").append(toIndentedString(maxRetries)).append("\n");
    sb.append("    commitIsolationEnabled: ").append(toIndentedString(commitIsolationEnabled)).append("\n");
    sb.append("    changesetFilterPatternRegex: ").append(toIndentedString(changesetFilterPatternRegex)).append("\n");
    sb.append("    filterFilePatternOption: ").append(toIndentedString(filterFilePatternOption)).append("\n");
    sb.append("    filterFilePatternRegex: ").append(toIndentedString(filterFilePatternRegex)).append("\n");
    sb.append("    _configuration: ").append(toIndentedString(_configuration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

