/*
 * Bamboo
 * This is the reference document for the Atlassian Bamboo REST API. The REST API is for developers who want to:    - integrate Bamboo with other applications;   - create scripts that interact with Bamboo; or   - develop plugins that enhance the Bamboo UI, using REST to interact with the backend.    You can read more about developing Bamboo plugins in the [Bamboo Developer Documentation](https://developer.atlassian.com/bamboo/server/docs/latest/).
 *
 * The version of the OpenAPI document: 9.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package me.glindholm.mylyn.bamboo.internal.rest.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Arrays;
import me.glindholm.mylyn.bamboo.internal.rest.model.RestDeploymentVersionStatus;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * VersionPreview
 */
@JsonPropertyOrder({
  VersionPreview.JSON_PROPERTY_ID,
  VersionPreview.JSON_PROPERTY_NAME,
  VersionPreview.JSON_PROPERTY_PLAN_BRANCH_NAME,
  VersionPreview.JSON_PROPERTY_DIFFERENT_BRANCH_AS_PREVIOUS_RELEASE,
  VersionPreview.JSON_PROPERTY_ISSUE_COUNT,
  VersionPreview.JSON_PROPERTY_ISSUE_URL,
  VersionPreview.JSON_PROPERTY_COMMIT_COUNT,
  VersionPreview.JSON_PROPERTY_COMMIT_URL,
  VersionPreview.JSON_PROPERTY_NUM_ENVIRONMENTS,
  VersionPreview.JSON_PROPERTY_NUM_ENVIRONMENTS_DEPLOYED_SUCCESSFUL,
  VersionPreview.JSON_PROPERTY_NUM_ENVIRONMENTS_DEPLOYED_FAILED,
  VersionPreview.JSON_PROPERTY_VERSION_STATUS,
  VersionPreview.JSON_PROPERTY_ROLLBACK,
  VersionPreview.JSON_PROPERTY_PREVIOUS_VERSION_NAME,
  VersionPreview.JSON_PROPERTY_PREVIOUS_VERSION_ID,
  VersionPreview.JSON_PROPERTY_LAST_CREATED_VERSION_NAME,
  VersionPreview.JSON_PROPERTY_LAST_CREATED_VERSION_ID,
  VersionPreview.JSON_PROPERTY_DIFFERENT_BUILD_PLAN
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class VersionPreview implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ID = "id";
  private Long id;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_PLAN_BRANCH_NAME = "planBranchName";
  private String planBranchName;

  public static final String JSON_PROPERTY_DIFFERENT_BRANCH_AS_PREVIOUS_RELEASE = "differentBranchAsPreviousRelease";
  private Boolean differentBranchAsPreviousRelease;

  public static final String JSON_PROPERTY_ISSUE_COUNT = "issueCount";
  private Integer issueCount;

  public static final String JSON_PROPERTY_ISSUE_URL = "issueUrl";
  private String issueUrl;

  public static final String JSON_PROPERTY_COMMIT_COUNT = "commitCount";
  private Integer commitCount;

  public static final String JSON_PROPERTY_COMMIT_URL = "commitUrl";
  private String commitUrl;

  public static final String JSON_PROPERTY_NUM_ENVIRONMENTS = "numEnvironments";
  private Integer numEnvironments;

  public static final String JSON_PROPERTY_NUM_ENVIRONMENTS_DEPLOYED_SUCCESSFUL = "numEnvironmentsDeployedSuccessful";
  private Integer numEnvironmentsDeployedSuccessful;

  public static final String JSON_PROPERTY_NUM_ENVIRONMENTS_DEPLOYED_FAILED = "numEnvironmentsDeployedFailed";
  private Integer numEnvironmentsDeployedFailed;

  public static final String JSON_PROPERTY_VERSION_STATUS = "versionStatus";
  private RestDeploymentVersionStatus versionStatus;

  public static final String JSON_PROPERTY_ROLLBACK = "rollback";
  private Boolean rollback;

  public static final String JSON_PROPERTY_PREVIOUS_VERSION_NAME = "previousVersionName";
  private String previousVersionName;

  public static final String JSON_PROPERTY_PREVIOUS_VERSION_ID = "previousVersionId";
  private Long previousVersionId;

  public static final String JSON_PROPERTY_LAST_CREATED_VERSION_NAME = "lastCreatedVersionName";
  private String lastCreatedVersionName;

  public static final String JSON_PROPERTY_LAST_CREATED_VERSION_ID = "lastCreatedVersionId";
  private Long lastCreatedVersionId;

  public static final String JSON_PROPERTY_DIFFERENT_BUILD_PLAN = "differentBuildPlan";
  private Boolean differentBuildPlan;

  public VersionPreview() { 
  }

  public VersionPreview id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(Long id) {
    this.id = id;
  }


  public VersionPreview name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public VersionPreview planBranchName(String planBranchName) {
    this.planBranchName = planBranchName;
    return this;
  }

   /**
   * Get planBranchName
   * @return planBranchName
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_PLAN_BRANCH_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPlanBranchName() {
    return planBranchName;
  }


  @JsonProperty(JSON_PROPERTY_PLAN_BRANCH_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPlanBranchName(String planBranchName) {
    this.planBranchName = planBranchName;
  }


  public VersionPreview differentBranchAsPreviousRelease(Boolean differentBranchAsPreviousRelease) {
    this.differentBranchAsPreviousRelease = differentBranchAsPreviousRelease;
    return this;
  }

   /**
   * Get differentBranchAsPreviousRelease
   * @return differentBranchAsPreviousRelease
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_DIFFERENT_BRANCH_AS_PREVIOUS_RELEASE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDifferentBranchAsPreviousRelease() {
    return differentBranchAsPreviousRelease;
  }


  @JsonProperty(JSON_PROPERTY_DIFFERENT_BRANCH_AS_PREVIOUS_RELEASE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDifferentBranchAsPreviousRelease(Boolean differentBranchAsPreviousRelease) {
    this.differentBranchAsPreviousRelease = differentBranchAsPreviousRelease;
  }


  public VersionPreview issueCount(Integer issueCount) {
    this.issueCount = issueCount;
    return this;
  }

   /**
   * Get issueCount
   * @return issueCount
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_ISSUE_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getIssueCount() {
    return issueCount;
  }


  @JsonProperty(JSON_PROPERTY_ISSUE_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIssueCount(Integer issueCount) {
    this.issueCount = issueCount;
  }


  public VersionPreview issueUrl(String issueUrl) {
    this.issueUrl = issueUrl;
    return this;
  }

   /**
   * Get issueUrl
   * @return issueUrl
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_ISSUE_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIssueUrl() {
    return issueUrl;
  }


  @JsonProperty(JSON_PROPERTY_ISSUE_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIssueUrl(String issueUrl) {
    this.issueUrl = issueUrl;
  }


  public VersionPreview commitCount(Integer commitCount) {
    this.commitCount = commitCount;
    return this;
  }

   /**
   * Get commitCount
   * @return commitCount
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_COMMIT_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCommitCount() {
    return commitCount;
  }


  @JsonProperty(JSON_PROPERTY_COMMIT_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommitCount(Integer commitCount) {
    this.commitCount = commitCount;
  }


  public VersionPreview commitUrl(String commitUrl) {
    this.commitUrl = commitUrl;
    return this;
  }

   /**
   * Get commitUrl
   * @return commitUrl
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_COMMIT_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCommitUrl() {
    return commitUrl;
  }


  @JsonProperty(JSON_PROPERTY_COMMIT_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommitUrl(String commitUrl) {
    this.commitUrl = commitUrl;
  }


  public VersionPreview numEnvironments(Integer numEnvironments) {
    this.numEnvironments = numEnvironments;
    return this;
  }

   /**
   * Get numEnvironments
   * @return numEnvironments
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_NUM_ENVIRONMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNumEnvironments() {
    return numEnvironments;
  }


  @JsonProperty(JSON_PROPERTY_NUM_ENVIRONMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNumEnvironments(Integer numEnvironments) {
    this.numEnvironments = numEnvironments;
  }


  public VersionPreview numEnvironmentsDeployedSuccessful(Integer numEnvironmentsDeployedSuccessful) {
    this.numEnvironmentsDeployedSuccessful = numEnvironmentsDeployedSuccessful;
    return this;
  }

   /**
   * Get numEnvironmentsDeployedSuccessful
   * @return numEnvironmentsDeployedSuccessful
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_NUM_ENVIRONMENTS_DEPLOYED_SUCCESSFUL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNumEnvironmentsDeployedSuccessful() {
    return numEnvironmentsDeployedSuccessful;
  }


  @JsonProperty(JSON_PROPERTY_NUM_ENVIRONMENTS_DEPLOYED_SUCCESSFUL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNumEnvironmentsDeployedSuccessful(Integer numEnvironmentsDeployedSuccessful) {
    this.numEnvironmentsDeployedSuccessful = numEnvironmentsDeployedSuccessful;
  }


  public VersionPreview numEnvironmentsDeployedFailed(Integer numEnvironmentsDeployedFailed) {
    this.numEnvironmentsDeployedFailed = numEnvironmentsDeployedFailed;
    return this;
  }

   /**
   * Get numEnvironmentsDeployedFailed
   * @return numEnvironmentsDeployedFailed
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_NUM_ENVIRONMENTS_DEPLOYED_FAILED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNumEnvironmentsDeployedFailed() {
    return numEnvironmentsDeployedFailed;
  }


  @JsonProperty(JSON_PROPERTY_NUM_ENVIRONMENTS_DEPLOYED_FAILED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNumEnvironmentsDeployedFailed(Integer numEnvironmentsDeployedFailed) {
    this.numEnvironmentsDeployedFailed = numEnvironmentsDeployedFailed;
  }


  public VersionPreview versionStatus(RestDeploymentVersionStatus versionStatus) {
    this.versionStatus = versionStatus;
    return this;
  }

   /**
   * Get versionStatus
   * @return versionStatus
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_VERSION_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestDeploymentVersionStatus getVersionStatus() {
    return versionStatus;
  }


  @JsonProperty(JSON_PROPERTY_VERSION_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersionStatus(RestDeploymentVersionStatus versionStatus) {
    this.versionStatus = versionStatus;
  }


  public VersionPreview rollback(Boolean rollback) {
    this.rollback = rollback;
    return this;
  }

   /**
   * Get rollback
   * @return rollback
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_ROLLBACK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getRollback() {
    return rollback;
  }


  @JsonProperty(JSON_PROPERTY_ROLLBACK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRollback(Boolean rollback) {
    this.rollback = rollback;
  }


  public VersionPreview previousVersionName(String previousVersionName) {
    this.previousVersionName = previousVersionName;
    return this;
  }

   /**
   * Get previousVersionName
   * @return previousVersionName
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_PREVIOUS_VERSION_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPreviousVersionName() {
    return previousVersionName;
  }


  @JsonProperty(JSON_PROPERTY_PREVIOUS_VERSION_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPreviousVersionName(String previousVersionName) {
    this.previousVersionName = previousVersionName;
  }


  public VersionPreview previousVersionId(Long previousVersionId) {
    this.previousVersionId = previousVersionId;
    return this;
  }

   /**
   * Get previousVersionId
   * @return previousVersionId
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_PREVIOUS_VERSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getPreviousVersionId() {
    return previousVersionId;
  }


  @JsonProperty(JSON_PROPERTY_PREVIOUS_VERSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPreviousVersionId(Long previousVersionId) {
    this.previousVersionId = previousVersionId;
  }


  public VersionPreview lastCreatedVersionName(String lastCreatedVersionName) {
    this.lastCreatedVersionName = lastCreatedVersionName;
    return this;
  }

   /**
   * Get lastCreatedVersionName
   * @return lastCreatedVersionName
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_LAST_CREATED_VERSION_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLastCreatedVersionName() {
    return lastCreatedVersionName;
  }


  @JsonProperty(JSON_PROPERTY_LAST_CREATED_VERSION_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastCreatedVersionName(String lastCreatedVersionName) {
    this.lastCreatedVersionName = lastCreatedVersionName;
  }


  public VersionPreview lastCreatedVersionId(Long lastCreatedVersionId) {
    this.lastCreatedVersionId = lastCreatedVersionId;
    return this;
  }

   /**
   * Get lastCreatedVersionId
   * @return lastCreatedVersionId
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_LAST_CREATED_VERSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getLastCreatedVersionId() {
    return lastCreatedVersionId;
  }


  @JsonProperty(JSON_PROPERTY_LAST_CREATED_VERSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastCreatedVersionId(Long lastCreatedVersionId) {
    this.lastCreatedVersionId = lastCreatedVersionId;
  }


  public VersionPreview differentBuildPlan(Boolean differentBuildPlan) {
    this.differentBuildPlan = differentBuildPlan;
    return this;
  }

   /**
   * Get differentBuildPlan
   * @return differentBuildPlan
  **/
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_DIFFERENT_BUILD_PLAN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDifferentBuildPlan() {
    return differentBuildPlan;
  }


  @JsonProperty(JSON_PROPERTY_DIFFERENT_BUILD_PLAN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDifferentBuildPlan(Boolean differentBuildPlan) {
    this.differentBuildPlan = differentBuildPlan;
  }


  /**
   * Return true if this VersionPreview object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VersionPreview versionPreview = (VersionPreview) o;
    return Objects.equals(this.id, versionPreview.id) &&
        Objects.equals(this.name, versionPreview.name) &&
        Objects.equals(this.planBranchName, versionPreview.planBranchName) &&
        Objects.equals(this.differentBranchAsPreviousRelease, versionPreview.differentBranchAsPreviousRelease) &&
        Objects.equals(this.issueCount, versionPreview.issueCount) &&
        Objects.equals(this.issueUrl, versionPreview.issueUrl) &&
        Objects.equals(this.commitCount, versionPreview.commitCount) &&
        Objects.equals(this.commitUrl, versionPreview.commitUrl) &&
        Objects.equals(this.numEnvironments, versionPreview.numEnvironments) &&
        Objects.equals(this.numEnvironmentsDeployedSuccessful, versionPreview.numEnvironmentsDeployedSuccessful) &&
        Objects.equals(this.numEnvironmentsDeployedFailed, versionPreview.numEnvironmentsDeployedFailed) &&
        Objects.equals(this.versionStatus, versionPreview.versionStatus) &&
        Objects.equals(this.rollback, versionPreview.rollback) &&
        Objects.equals(this.previousVersionName, versionPreview.previousVersionName) &&
        Objects.equals(this.previousVersionId, versionPreview.previousVersionId) &&
        Objects.equals(this.lastCreatedVersionName, versionPreview.lastCreatedVersionName) &&
        Objects.equals(this.lastCreatedVersionId, versionPreview.lastCreatedVersionId) &&
        Objects.equals(this.differentBuildPlan, versionPreview.differentBuildPlan);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, planBranchName, differentBranchAsPreviousRelease, issueCount, issueUrl, commitCount, commitUrl, numEnvironments, numEnvironmentsDeployedSuccessful, numEnvironmentsDeployedFailed, versionStatus, rollback, previousVersionName, previousVersionId, lastCreatedVersionName, lastCreatedVersionId, differentBuildPlan);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VersionPreview {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    planBranchName: ").append(toIndentedString(planBranchName)).append("\n");
    sb.append("    differentBranchAsPreviousRelease: ").append(toIndentedString(differentBranchAsPreviousRelease)).append("\n");
    sb.append("    issueCount: ").append(toIndentedString(issueCount)).append("\n");
    sb.append("    issueUrl: ").append(toIndentedString(issueUrl)).append("\n");
    sb.append("    commitCount: ").append(toIndentedString(commitCount)).append("\n");
    sb.append("    commitUrl: ").append(toIndentedString(commitUrl)).append("\n");
    sb.append("    numEnvironments: ").append(toIndentedString(numEnvironments)).append("\n");
    sb.append("    numEnvironmentsDeployedSuccessful: ").append(toIndentedString(numEnvironmentsDeployedSuccessful)).append("\n");
    sb.append("    numEnvironmentsDeployedFailed: ").append(toIndentedString(numEnvironmentsDeployedFailed)).append("\n");
    sb.append("    versionStatus: ").append(toIndentedString(versionStatus)).append("\n");
    sb.append("    rollback: ").append(toIndentedString(rollback)).append("\n");
    sb.append("    previousVersionName: ").append(toIndentedString(previousVersionName)).append("\n");
    sb.append("    previousVersionId: ").append(toIndentedString(previousVersionId)).append("\n");
    sb.append("    lastCreatedVersionName: ").append(toIndentedString(lastCreatedVersionName)).append("\n");
    sb.append("    lastCreatedVersionId: ").append(toIndentedString(lastCreatedVersionId)).append("\n");
    sb.append("    differentBuildPlan: ").append(toIndentedString(differentBuildPlan)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

